name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        java: [23]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Build and Test
        run: ./build_and_test.sh
